# Generated by Django 4.2.8 on 2023-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
